### ISSUE TITLE
Can't find it in Package Control

### ISSUE THREAD

**Issue by tino** [SublimeLinter/SublimeLinter-pyyaml#5]
Not from sublime text, nor here: https://packagecontrol.io/search/yaml

**Comment by NotSqrt** [comment]
https://packagecontrol.io/packages/SublimeLinter-pyyaml

**Comment by optyler** [comment]
As the previous comment, I can't find the package with package manager. here after some screen captures.

How can I be sure that I am using the [packagecontrol.io](https://packagecontrol.io/packages/SublimeLinter-pyyaml) _market_?

<img width="684" alt="capture d ecran 2017-03-03 a 15 18 03" src="https://cloud.githubusercontent.com/assets/10259/23554300/c21ba5ba-0024-11e7-9659-de78ba7fd793.png">
<img width="604" alt="capture d ecran 2017-03-03 a 15 18 32" src="https://cloud.githubusercontent.com/assets/10259/23554299/c20f333e-0024-11e7-920a-1420c13b47e6.png">

**Comment by tino** [comment]
Ah, found it. Reported that here https://github.com/wbond/packagecontrol.io/issues/65
