### ISSUE TITLE
Doesn't like different yaml tags

### ISSUE THREAD

**Issue by adamchainz** [SublimeLinter/SublimeLinter-pyyaml#6]
This is valid YAML:

```
!foo valid yaml
```

Which would construct a 'foo' object when loaded by the right program. But because the linter calls a simple load, PyYAML raises `ConstructorError` as it hasn't been told how to load `foo` objects:

![screen shot 2016-09-20 at 17 56 14](https://cloud.githubusercontent.com/assets/857609/18680510/e006f20e-7f5b-11e6-91d7-035591173274.png)

[`yamllint`](https://github.com/adrienverge/yamllint) fixes this and also lints some other oddities like repeated keys, perhaps it would be better to use that rather than `PyYAML` directly? If not the way it avoids `ConstructorError` could at least be copied.

**Comment by adamchainz** [comment]
It uses `yaml.parse` rather than `safe_load_all` https://github.com/adrienverge/yamllint/blob/master/yamllint/linter.py#L169

**Comment by NotSqrt** [comment]
Well, then that would be a different linter !
You can create a SublimeLinter-yamllint linter if you want !

**Comment by adamchainz** [comment]
I'm going to use `yaml.parse` here 😄

**Comment by NotSqrt** [comment]
The new version should be available in package control in the next hour.
