### ISSUE TITLE
Not found in package control panel

### ISSUE THREAD

**Issue by optyler** [SublimeLinter/SublimeLinter-pyyaml#9]
As in the previous issue #5 , I can't find the package with package manager. here after some screen captures.

How can I be sure that I am using the [packagecontrol.io](https://packagecontrol.io/packages/SublimeLinter-pyyaml) _market_?

<img width="684" alt="capture d ecran 2017-03-03 a 15 18 03" src="https://cloud.githubusercontent.com/assets/10259/23554300/c21ba5ba-0024-11e7-9659-de78ba7fd793.png">
<img width="604" alt="capture d ecran 2017-03-03 a 15 18 32" src="https://cloud.githubusercontent.com/assets/10259/23554299/c20f333e-0024-11e7-920a-1420c13b47e6.png">

**Comment by NotSqrt** [comment]
Are you sure it's not already installed ?

![capture d ecran de 2017-03-13 09 10 56](https://cloud.githubusercontent.com/assets/1997005/23846296/1e2fdefc-07cd-11e7-9312-2462fd801d7e.png)

**Comment by optyler** [comment]
You are right!

I was thinking that duplicate keys in `yml` file will generate some error or warnings... and I supposed that the linter was not installed. sorry for the inconvinience...
